### ISSUE TITLE
No such service

### ISSUE THREAD

**Issue by Deepseath** [wallace5303/dnnmmp#4]
安装很多都报“No such service”错误。
docker-compose up -d phpredisadmin
No such service: phpredisadmin

docker-compose up -d adminmongo
No such service: adminmongo

$ docker-compose ps 如下。

      Name                    Command               State                     Ports
-----------------------------------------------------------------------------------------------------
dnnmmp_go_1        /bin/sh                         Exit 0                       
dnnmmp_mongodb_1   docker-entrypoint.sh --auth     Exit 14                      
dnnmmp_nginx_1     nginx -g daemon off;            Up        0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
dnnmmp_php73_1     docker-php-entrypoint php-fpm   Up        0.0.0.0:9003->9000/tcp
dnnmmp_redis_1     redis-server /etc/redis.conf    Up        0.0.0.0:6379->6379/tcp
dnnmmp_yapi_1      entrypoint.sh                   Up        0.0.0.0:8005->8005/tcp

**Comment by Deepseath** [comment]
git 用的是 master 分支

**Comment by wallace5303** [comment]
这两个我文档中写的应该是开发中，不过快好了

**Comment by Deepseath** [comment]
> 这两个我文档中写的应该是开发中，不过快好了

嗯嗯，加油！！期待。
